name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
env:
  BuildConfig: Release
  SolutionFile: Poi.sln

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1
    - name: Install dependencies
      working-directory: ./apis/pois
      run: dotnet restore
    
    - name: Build
      run:
        dotnet build --configuration Release --no-restore
      working-directory: ./apis/pois
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      working-directory: ./apis/pois
